version: '3.8' 
services: # apps containers you want to build and run
  pooja-app1: # name of appliction for compose 
    image: poojadotnetimg:v1  # image i want to build 
    build: .  # path of dockerfile location -- . means current 
    container_name: poojac1 # it will create container also 
  pooja-app2: 
    image: poojahttpd:v1 
    build: 
      context: . #location of dockerfile 
      dockerfile: httpd.dockerfile # name of dockerfile 
    container_name: poojac2 
    ports:
      - 1027:80  
  
